Repository cakephp/app, pull requests merged in 2023-07, with the labels that each got.

#958 5.x: update dependencies
  composer.json
Labels: Dependencies

#959 Use file config instead.
  .github/workflows/ci.yml
  composer.json
  phpcs.xml
Labels: Configuration

#960 Set return type for closures
  config/routes.php
Labels: Code Style
